### GET ALL TASKS
GET http://localhost:3000/api/v1/tasks HTTP/1.1

### ADD A NEW TASK
POST http://localhost:3000/api/v1/tasks HTTP/1.1
content-type: application/json

{
    "text": "buy something",
    "completed": 0,
    "priority": 0
}

### UPDATE A TASK
PATCH http://localhost:3000/api/v1/tasks/2 HTTP/1.1
content-type: application/json

{
    "completed": 1
}

### DELETE A TASK
DELETE http://localhost:3000/api/v1/tasks/4 HTTP/1.1